-- Insert data engineering related keywords
-- Categories: database, data_warehouse, processing_engine, streaming, orchestration, etl_tool, platform, concept
INSERT INTO data_engineering_keywords (keyword, category) VALUES
    ('DuckDB', 'database'),
    ('ClickHouse', 'database'),
    ('PostgreSQL', 'database'),
    ('Apache_Cassandra', 'database'),
    ('MongoDB', 'database'),
    ('Redis', 'database'),
    ('Snowflake_(company)', 'data_warehouse'),
    ('BigQuery', 'data_warehouse'),
    ('Amazon_Redshift', 'data_warehouse'),
    ('Azure_Synapse_Analytics', 'data_warehouse'),
    ('Apache_Spark', 'processing_engine'),
    ('Apache_Flink', 'processing_engine'),
    ('Apache_Beam', 'processing_engine'),
    ('Presto_(SQL_query_engine)', 'processing_engine'),
    ('Apache_Kafka', 'streaming'),
    ('Apache_Pulsar', 'streaming'),
    ('RabbitMQ', 'streaming'),
    ('Apache_Airflow', 'orchestration'),
    ('Prefect_(software)', 'orchestration'),
    ('Dagster', 'orchestration'),
    ('dbt_(software)', 'etl_tool'),
    ('Fivetran', 'etl_tool'),
    ('Airbyte', 'etl_tool'),
    ('Databricks', 'platform'),
    ('Data_engineering', 'concept'),
    ('Extract,_transform,_load', 'concept'),
    ('Data_warehouse', 'concept'),
    ('Data_lake', 'concept'),
    ('Data_pipeline', 'concept');
